---
- name: install wget
  pacman: name=wget state=present
  tags: wget
  become: true

- name: install git
  pacman: name=git state=present
  tags: git
  become: true

- name: install emacs
  pacman: name=emacs state=present
  tags: emacs
  become: true

- name: install chromium
  pacman: name=chromium state=present
  become: true

- name: install virtualbox
  pacman: name=virtualbox state=present
  become: true

- name: install ruby
  pacman: name=ruby state=present
  become: true

- name: install ag
  pacman: name=the_silver_searcher state=present
  become: true
  
- name: install i3-gaps
  pacman: name=i3-gaps state=present
  become: true
